[package]
name = "veb-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
ghost = "0.1"
hashbrown = "0.13"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "random"
harness = false

[lib]
bench = false
